### ISSUE TITLE
Modifying code to also upload PDFS 

### ISSUE THREAD

**Issue by KeertikaYOGENDRA** [Alexmhack/Django-Multiple-File-Uploads-AJAX#1]
Hi, 

Thank you for your open source code it is incredibly helpful ! I wanted to ask where exactly do I need to modify the code to get it to also upload pdf ? Thank you so much !

**Comment by Alexmhack** [comment]
Hi @KeertikaYOGENDRA 

I think uploading PDFs should work by default, can you try uploading once and see if it works.

**Comment by Alexmhack** [comment]
The only change you would need is in the _photos/models.py_,

```
class Photo(models.Model):
	title = models.CharField(max_length=256, blank=True, null=True)
	file = models.FileField(upload_to=photo_directory_path)  # ImageField -> FileFIeld
	timestamp = models.DateTimeField(auto_now=True)
	updated = models.DateTimeField(auto_now_add=True)
```

then run `makemigrations` & `migrate` to update the database

**Comment by KeertikaYOGENDRA** [comment]
Yup it works thank you so much !
